version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    main: ./cmd/{{ .ProjectName }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" -}}
        x86_64
      {{- else if eq .Arch "386" -}}
        i386
      {{- else }}
        {{- .Arch }}
      {{- end }}
      {{- if .Arm -}}
        v{{ .Arm }}
      {{- end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - &amd64ImageName ghcr.io/jtyr/docker/{{ .ProjectName }}:{{ .Tag }}-amd64
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
  - image_templates:
      - &arm64ImageName ghcr.io/jtyr/docker/{{ .ProjectName }}:{{ .Tag }}-arm64
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
    goarch: arm64

docker_manifests:
  - name_template: ghcr.io/jtyr/docker/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - *amd64ImageName
      - *arm64ImageName
  - name_template: ghcr.io/jtyr/docker/{{ .ProjectName }}:latest
    image_templates:
      - *amd64ImageName
      - *arm64ImageName
