{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "gwm.fullname" . }}
  labels: {{- include "gwm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "gwm.fullname" . }}
  minReplicas: {{ .Values.autoscaling.replicas.min }}
  maxReplicas: {{ .Values.autoscaling.replicas.max }}
  metrics:
    {{- with .Values.autoscaling.targetUtilization.cpu }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
    {{- end }}
    {{- with .Values.autoscaling.targetUtilization.memory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
    {{- end }}
{{- end }}
